backend:
  name: git-gateway
  branch: master
media_folder: 'static/img'
public_folder: '/img'
# local_backend: true
collections:
  - name: 'test'
    label: 'test'
    folder: 'src/lib/data/test'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
